---

- name: First Ansible Try(03 Testing the setup)
  hosts: cisco
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: "OSPF CONFIG"
      cisoc.ios.ios_config:
        line:
          - router-id 99.99.99.99
        parents:
          - router ospf 99
      register: ospf_out

    - debug: var=ospf_out 
