---

- name: "conditional logical test"
  hosts: usa
  gather_facts: false
  connection: network_cli
 
  
  tasks:
    - name: "Gather facts"
      cisco.ios.ios_facts:
        gather_subset: all
    
    - name: "print gather facts"
      debug: 
        msg: "Interface {{ item['key'] }} has an IP address of {{ item['value']['ipv4'][0]['address'] }}"
      loop: "{{ ansible_net_interfaces | dict2items }}"
      #when: item['value']['lineprotocol'] =="up"
      when: item['value']['ipv4'] != []