---
- name: "IP filter test"
  hosts: "192.168.10.102"
  gather_facts: false

  tasks:
    - name: "IP address filter stuff"
      vars:
        #myip: 
        #  - "192.168.55.1"
        #  - "192.168.555.1"
        #  - "2001:1234:1234::1"
        #  - "2001:abcd:defg::1"
        #  - "8.8.8.8"
        myip: "192.168.1.1/24"

      #debug:
        #msg: "{{ myip | ansible.utils.ipaddr }}"
      
      #debug:
        #msg: "{{ myip | ansible.utils.ipv4 }}"

      #debug:
        #msg: "{{ myip | ansible.utils.ipv6 }}"
      
      #debug:
        #msg: "{{ myip | ansible.utils.ipaddr('address') }}"
      
      debug:
        msg: "{{ myip | ansible.utils.ipaddr('network') }}"