---

- name: "test some variable substition"
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1"
      cisco.ios.ios_config:
        src: bgp.condition.j2   #automatic search directory templates. 
