---

- name: "REGESTER PLAYBOOK"
  hosts: 192.168.10.101
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "push configure"
      cisco.ios.ios_config:
        src: "ntp.j2"
      notify: ntp_handler_example
      register: ntp_result

#  handlers:
#    - name: ntp_handler_example
#      debug:
#        msg: "{{ ntp_result }}"
   
  handlers:
    - name: "Not match notify specify name,must use listen reference notify"
      listen: ntp_handler_example
      debug:
       msg: "CONFIGURE CHANGE: {{ ntp_result.commands }}"