---

- name: loop pratice
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Gather info"
      cisco.ios.ios_facts:
        gather_subset: all

    - name: "Print return information from the previous task"
      debug:
        msg: "{{ ansible_facts }}"
